pipeline {
    agent {
        
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                sh 'mvn -B -DskipTests clean deploy'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
           
        }
    }
}
